#----- DIRECTORY -----
app.bayes.directory.rootDirectory=$$user.home$$/AR_Tools/bayes_solver/
app.bayes.directory.printerDirectory=output/
app.bayes.directory.saveDirectory=saved_networks/
#----- INFERENCE -----
app.bayes.inference.defaultInferenceAlgorithm=JUNCTION_TREE_ALGORITHM
#----- SOLVER --------
app.bayes.solver.defaultSolverAlgorithm=JUNCTION_TREE_IPFP
app.bayes.solver.cyclesLimit=100000
app.bayes.solver.timeLimitSeconds=120
app.bayes.solver.logSolverProgress=true
app.bayes.solver.logIntervalSeconds=5
app.bayes.solver.convergeThreshold=1e-16
#----- INTERNAL ------
app.bayes.internal.doubleEqualityPrecision=1e-16
#----- PRINTER -------
app.bayes.printer.openFileOnCreation=true
app.bayes.printer.openFolderOnCreation=true
app.bayes.printer.printToConsole=false
app.bayes.printer.printToTextFile=true
app.bayes.printer.probDecimalPlaces=6
#----- EXTENSION -----
app.bayes.extension.fileExtension=.bayes