#----- DIRECTORY -----
app.directory.rootDirectory=$$user.home$$/AR_Tools/bayes_solver/
app.directory.printerDirectory=output/
app.directory.saveDirectory=saved_networks/
#----- INFERENCE -----
app.inference.defaultInferenceAlgorithm=JUNCTION_TREE_ALGORITHM
#----- SOLVER --------
app.solver.defaultSolverAlgorithm=JUNCTION_TREE_IPFP
app.solver.cyclesLimit=100000
app.solver.timeLimitSeconds=120
app.solver.logSolverProgress=true
app.solver.logIntervalSeconds=5
app.solver.convergeThreshold=1e-16
#----- INTERNAL ------
app.internal.doubleEqualityPrecision=1e-16
#----- PRINTER -------
app.printer.openFileOnCreation=true
app.printer.openFolderOnCreation=true
app.printer.printToConsole=false
app.printer.printToTextFile=true
app.printer.observedFileTitle=OBSERVED TABLES
app.printer.networkFileTitle=NETWORK TABLES
app.printer.probDecimalPlaces=6
#----- EXTENSION -----
app.extension.fileExtension=.bayes