app.inference.useJunctionTree=true
app.solver.cyclesLimit=1000
app.solver.timeLimitSeconds=120
app.solver.logSolverProgress=true
app.solver.logIntervalSeconds=5
app.solver.convergeThreshold=1e-9
app.printer.saveDirectory=$$user.home$$/AR_Tools/bayes_solver/output/
app.printer.openFileOnCreation=true
app.printer.openFolderOnCreation=true
app.printer.printToConsole=false
app.printer.printToTextFile=true
app.printer.observedFileTitle=OBSERVED TABLES
app.printer.networkFileTitle=NETWORK TABLES
app.printer.probDecimalPlaces=6
